# Generated by Django 5.2.4 on 2025-08-25 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('properties', '0003_roompricerule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditaccount',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='properties.partner'),
        ),
    ]
