# Generated by Django 5.2.4 on 2025-08-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_creditaccount_partner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
