# Generated by Django 5.2.4 on 2025-08-21 14:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roompricerule',
            name='price',
        ),
        migrations.AddField(
            model_name='roompricerule',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='roompricerule',
            name='mode',
            field=models.CharField(choices=[('ADD_FIXED_PER_GUEST', 'add fixed per guest'), ('PERCENT', 'add percent from base')], default='ADD_FIXED_PER_GUEST', max_length=50),
        ),
        migrations.AddField(
            model_name='roompricerule',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='10.00 = +10%, -15.00 = -15% ', max_digits=6, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='roompricerule',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='properties.room'),
        ),
    ]
