# Generated by Django 5.2.4 on 2025-08-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_roompricerule_price_roompricerule_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompricerule',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
