# Generated by Django 5.2.4 on 2025-08-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('awaiting_partner', 'Awaiting Partner Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='awaiting_partner', max_length=50),
        ),
    ]
