# Generated by Django 5.2.4 on 2025-09-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_sms_cancelled_sent',
            field=models.BooleanField(default=False),
        ),
    ]
